# docker network create nome-rede
# docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
services:
  mysql:
    image: mysql/mysql-server
    container_name: some-mysql
    restart: always
    environment:
      MYSQL_DATABASE: guaca_db
      MYSQL_USER: guaca_user
      MYSQL_PASSWORD: guaca_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
  guacd:
    image: guacamole/guacd
    container_name: some-guacd
    restart: always
  guacamole:
    image: guacamole/guacamole
    container_name: some-guacamole
    restart: always
    depends_on:
      - guacd
      - mysql
    environment:
      MYSQL_DATABASE: guaca_db
      MYSQL_USER: guaca_user
      MYSQL_PASSWORD: guaca_password
      WEBAPP_CONTEXT: ROOT
    ports:
      - "8080:8080"
networks:
  nome-rede:
    external: true
